//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.0
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections;


namespace Jackal.Domain
{
	public static class Enumerator
	{
		public static IEnumerator Concat(params IEnumerator[] lists)
		{
			foreach (var values in lists)
				while (values.MoveNext()) {
					yield return values.Current;
				}
		}
	}
}

